const Menu = [{
    id : 1,
    image : "../images/maggi.jpg",
    name :"Maggi" ,
    catagory : "evening",
    price: "15 rupees",
    description : "A delicious bowl of instant noodles cooked with flavorful spices, fresh vegetables, and aromatic seasonings. Prepared fresh and served hot, it is a perfect choice for a quick, tasty, and satisfying meal.",
},
{
    id : 2,
    image : "../images/pakoda.jpg",
    name : "Bread Pakoda",
    catagory : "breakfast",
    price: "20 rupees",
    description : "Bread Pakora is a popular crispy snack made by coating fresh bread slices in a seasoned gram flour batter and deep-frying them until golden brown. It is served hot with tangy green chutney and ketchup for a delightful taste.",
},
{
    id : 3,
    image : "../images/pizza.jpg",
    name : "Pizza" ,
    catagory : "evening",
    price : "70 rupees",
    description : "Our freshly baked pizza features a crispy crust topped with rich mozzarella cheese, fresh vegetables, flavorful pizza sauce, and Italian herbs. Every slice offers a perfect combination of cheesy goodness and delicious flavors.",
},
{
    id : 4,
    image : "../images/non-veg.jpg",
    name : "Non-Veg Thali",
    catagory : "Dinner",
    price : "150 rupees",
    description : "A complete and satisfying meal featuring flavorful non-vegetarian curry, rice, fresh rotis, dal, seasonal vegetables, salad, and pickle. Prepared with authentic spices for a rich and memorable dining experience.",
},
{
    id : 5,
    image : "../images/sandwitch.jpg",
    name : "Cheese Sandwitch",
    catagory : "breakfast",
    price : " 30 rupees",
    description : "Prepared with fresh bread, crunchy vegetables, creamy spreads, and melted cheese, our sandwich is both wholesome and delicious. It is grilled to perfection and makes a perfect light meal or snack.",
},
{
    id : 6,
    image : "../images/rice.jpg",
    name : "Jeera Rice & Dal Makhni",
    catagory : "Dinner",
    price : "150 rupees",
    description : "Steamed basmati rice delicately flavored with cumin seeds, butter, and mild spices. Light, aromatic, and the perfect accompaniment to dals, curries, and gravies.",
},
{
    id : 7,
    image : "../images/pulao.jpg",
    name : "Pulao & Khadai Paneer",
    catagory : "lunch",
    price : "100 rupees",
    description : "A flavorful vegetable pulao cooked with fragrant basmati rice, aromatic spices, and fresh vegetables, served with rich and creamy paneer curry. A wholesome meal that perfectly blends taste and tradition.",
},
{
    id : 8,
    image : "../images/idli.jpg",
    name : "Idli with Coconut Chatni",
    catagory : "breakfast",
    price : "40 rupees",
    description : "Soft, fluffy, and steamed to perfection, our idlis are made from a fermented rice and lentil batter. Served with hot sambar and fresh coconut chutney, they offer a healthy and authentic South Indian dining experience.",
},
{
    id : 9,
    image : "../images/spring.jpg",
    name : "spring roll",
    catagory : "evening",
    price : "50 rupees",
    description : "Our crispy spring rolls are filled with a flavorful mixture of fresh vegetables wrapped in a thin pastry sheet and fried until golden. They are served with a spicy or sweet chili dipping sauce for an irresistible appetizer.",
},

]
export default Menu;

